### ISSUE TITLE
Suggestion for clarity

### ISSUE THREAD

**Issue by jethrosweb** [learn-co-curriculum/phase-0-git-pushing-code#7]
The 'Set the Destination of a Repo with Git Remote' section is confusing as it does not clearly specify that you need to paste the repository path following this terminal command 'my_new_directory $ git remote add origin.'

My suggestion would be to change the above terminal command to match the one shown in the conclusion: 'git remote add origin your-remote-repository-URL'

**Comment by lizbur10** [comment]
Hi @jethrosweb ! Thanks for bringing this to our attention!

It appears that your Canvas course may have an older version of this lesson, which was edited substantially about a month ago. I've taken a look at the revised version and it looks like the point of confusion you identified is no longer present. 

Unfortunately, the update made to the prework last month included some major revisions and resequencing, so we were not able to update the courses for students who had already started the prework. You can see the changes that were made here in GitHub, in the README.md file, but be aware that there may be some things in it that don't pertain to your version of the prework.

I'm going to go ahead and close this issue, but please feel free to reopen it if you believe the source of the confusion still exists in the updated version of the lesson.

Thanks for contributing to the Flatiron School curriculum 💙
